---
- vars:
  vars_file_name: default_vars.yml
  db_master_password: "{{ lookup('aws_ssm', parampath ~ 'db_master_password', region='us-east-2', ) }}"
  old_db_password: "{{ lookup('aws_ssm', parampath ~ 'db_password', region='us-east-2', ) }}"
  new_db_password: '{{ lookup( 'password', '/dev/null' )

- hosts: localhost
  tasks:
    - name: set the password in the store to a new value
      asw_ssm_parameter_store:
        name: parampath ~ '/db_password'
        value: '{{new_db_password}}'
        secure_string: True
        overwrite: True
        string_type: SecureString
      notify: database password changed

- hosts: webservers
  handlers:
  - name: database password changed
    copy: 
      content: "{{ 'dbservers.mydomain.example.com:5432:main_db:my_user:' ~ new_db_password }}"
      dest: /etc/appdb_pgpass

- hosts: db_servers
  handlers: 
  - name: database password changed
    postgresql_user:
        login_host: dbservers.mydomain.example.com
        login_user: my_user
        login_password: "{{ new_db_password }}"
        port: 5432
